[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self'"

[template.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
